name: build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: actuated-4cpu-12gb
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@master
        with:
          go-version: 1.22.x
      - name: Make
        run: make all
